sudo: false
language: python
python:
  - '2.7'
env:
  global:
    - NIFTY_TRAVIS_CACHE_REPO=https://github.com/nimbis/travis-cache-public.git
install:
  - make reqs > /dev/null
before_script:
  - git clone https://github.com/nimbis/nifty.git ./.nifty
script:
  - ./.nifty/nifty-script nifty_test_app
notifications:
  email: false
